[hyperparameters]
# Spatial and angular resolution ranges
grid_cell_size = [0.0075]
quad_order = [6]

# Geometry ranges
green_center_x = [-0.1, 0.0, 0.1]
green_center_y = [-0.075, 0.0, 0.075]
red_right_top = [0.3, 0.4, 0.5]
red_right_bottom = [-0.5, -0.4, -0.3]
red_left_top = [0.3, 0.4, 0.5]
red_left_bottom = [-0.5, -0.4, -0.3]
horizontal_left = [-0.63, -0.6, -0.5]
horizontal_right = [0.5, 0.6, 0.63]
